// Auto-generate the better-auth tables in server/db/schema.ts.
//
// LAW: better-auth schemas are ALWAYS generated by the CLI, never hand-written.
// This script:
//   1. runs `bunx auth generate` against scripts/auth.config.ts (the plugin
//      mirror of server/utils/auth.ts)
//   2. post-processes: renames tables to tandem_*, adds the tandem_ FK on
//      apikey.referenceId (the generator emits no FK there), withTimezone
//   3. splices the result into server/db/schema.ts between the GENERATED
//      markers, leaving hand-owned Tandem domain tables untouched
//
// Usage: bun run gen:auth
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

const OUT = '/tmp/tandem-auth-schema.ts'
execSync(`bunx auth generate --config scripts/auth.config.ts --output ${OUT} -y`, { stdio: 'pipe' })
let gen = readFileSync(OUT, 'utf8')

// --- post-process ---
// canonical tandem table names
gen = gen.replaceAll('pgTable("user"', 'pgTable("tandem_user"')
gen = gen.replaceAll('pgTable("session"', 'pgTable("tandem_session"')
gen = gen.replaceAll('pgTable("account"', 'pgTable("tandem_account"')
gen = gen.replaceAll('pgTable("verification"', 'pgTable("tandem_verification"')
gen = gen.replaceAll('pgTable("apikey"', 'pgTable("tandem_apikey"')
// FK the generator omits: apikey.referenceId -> tandem_user
gen = gen.replace("referenceId: text('reference_id').notNull(),",
  "referenceId: text('reference_id').notNull().references(() => user.id, { onDelete: 'cascade' }),")
// timezone-aware timestamps (the whole app uses timestamptz)
gen = gen.replaceAll("timestamp('", "timestamp('")
gen = gen.replace(/timestamp\('([a-z_]+)'\)/g, "timestamp('$1', { withTimezone: true })")

// --- splice into schema.ts between markers ---
const SCHEMA = 'server/db/schema.ts'
let schema = readFileSync(SCHEMA, 'utf8')
const START = '// >>> BEGIN GENERATED better-auth tables (bun run gen:auth) — do not edit by hand'
const END = '// <<< END GENERATED better-auth tables'
const i = schema.indexOf(START)
const j = schema.indexOf(END)
if (i === -1 || j === -1) {
  console.error('markers missing in server/db/schema.ts')
  process.exit(1)
}
const body = gen.split('\n').filter(l => !l.startsWith('import')).join('\n')
schema = schema.slice(0, i + START.length) + '\n\n' + body + '\n\n' + schema.slice(j)
writeFileSync(SCHEMA, schema)
console.log('server/db/schema.ts regenerated from better-auth config')
